@startuml
autonumber
actor zh.vpk
database zh.epd.db
participant zh.epd.api
participant zh.broker.app
participant zh.broker.authserver
database zh.broker.rs
participant zh.broker.nutsnode.authserver
participant zh.broker.nutsnode.registry
participant vvt.ecd.nutsnode
participant vvt.ecd.app
actor vvt.vpk

zh.vpk --> zh.broker.app: log in
zh.broker.app --> zh.broker.rs: FHIR Task 
zh.broker.app --> zh.broker.nutsnode.authserver: request access en id token 
note left: is het nog nodig eerst een authorization code op te halen en zo ja waar?
zh.broker.app <-- zh.broker.nutsnode.authserver: access en id token
zh.broker.app --> zh.broker.nutsnode.registry: get endpoint vvt
note left: welke zoekparameters kan je/moet je meegeven? 
zh.broker.app <-- zh.broker.nutsnode.registry: endpoint url
zh.broker.app --> vvt.ecd.app: Notification (empty POST)

vvt.ecd.app <-- vvt.vpk: neem notificatie waar
vvt.ecd.nutsnode <-- vvt.ecd.app: request access en id token 
vvt.ecd.nutsnode --> vvt.ecd.app: access en id token
zh.broker.rs <-- vvt.ecd.app: GET /Task 
note right: GET request naar /Task voorzien van juiste tokens
zh.broker.rs --> vvt.ecd.app: FHIR Task
vvt.ecd.nutsnode <-- vvt.ecd.app: request access en id token 
note right: dit is een gebruikers authenticatie token toch?
vvt.ecd.nutsnode --> vvt.ecd.app: access en id token
zh.broker.rs <-- vvt.ecd.app: GET /Composition FHIR Resources Overdracht 
note right: loop niet nodig want get gaat om 1 Composition resource waar alle losse resources in zitten
zh.broker.rs --> zh.epd.api: GET X
zh.epd.api --> zh.epd.db: SQL X
zh.epd.api <-- zh.epd.db: SQL Result
zh.broker.rs <-- zh.epd.api: X
zh.broker.rs --> vvt.ecd.app: FHIR Composition Overdracht
vvt.ecd.app --> vvt.vpk: present overdracht
@enduml